config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :events, :concerns => :paginatable do
    resources :tickets, only: [:create, :destroy]
  end

  devise_for :users
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show] do
    resources :notifications, only: [:index, :destroy]
  end

  root 'events#index'

  get 'about' => 'static_pages#about'

  mount Markdown::API => '/'

end

app/models/event.rb
class Event < ActiveRecord::Base
  enum visibility: { everyone: 10, members_only: 20 }

  has_many :tickets
  has_many :attendees, through: :tickets, source: :user

  has_many :targets
  has_many :invitees, through: :targets, source: :user
  attr_accessor :members

  has_one :invitation, class_name: EventInvitation
  accepts_nested_attributes_for :invitation, allow_destroy: true

  belongs_to :owner, class_name: 'User'
  delegate :name, to: :owner, prefix: true

  has_many :notifications, as: :content

  mount_uploader :image_file, FileUploader

  validates :title, presence: true

  default_scope do
    includes(:owner, :targets, :attendees, :invitation)
      .order('event_invitations.start_time')
  end
  scope :coming, lambda {
    where('event_invitations.start_time > ?', Time.now)
      .order('event_invitations.start_time')
  }
  scope :passed, lambda {
    where('event_invitations.start_time < ?', Time.now)
      .reorder('event_invitations.start_time desc')
  }
  scope :visible, lambda { |user|
    if user.present?
      where('visibility is ? OR visibility = ? OR owner_id = ? OR targets.user_id = ?',
            nil, Event.visibilities[:everyone], user.id, user.id)
    else
      where('visibility is ? OR visibility = ?',
            nil, Event.visibilities[:everyone])
    end
  }

  def image?
    image_file? || image_url?
  end

  def image
    image_file_url || image_url
  end

  def owner?(user)
    return false unless user
    owner_id == user.id
  end

  def attend?(user)
    return false unless user
    tickets.find_by(user_id: user.id)
  end

  def attend!(user)
    tickets.find_or_create_by!(user_id: user.id)
  end

  def include?(user)
    owner == user || attend?(user)
  end

  def convert_invitees_to_member_ids
    self.members = invitees.map(&:id).join(',')
  end

  def invite!(user)
    targets.find_or_create_by!(user_id: user.id)

    user.notifications.create(
      description: I18n.t('view.notification.invited', event: title),
      content: self
    )
  end

  def uninvite!(user)
    target = targets.find_by!(user_id: user.id)
    target.destroy!

    Notification.find_and_checked!(user, self)
  end

  def convert_member_ids_to_invitees(members)
    old_ids = invitees.map(&:id)
    new_ids = members.present? ? members.split(',').map(&:to_i) : []

    added_ids = []
    new_ids.each do |id|
      added_ids.push id if old_ids.index(id).nil?
    end
    added_ids.each do |id|
      user = User.find(id)
      invite!(user) if user.present?
    end

    removed_ids = []
    old_ids.each do |id|
      removed_ids.push id if new_ids.index(id).nil?
    end
    removed_ids.each do |id|
      user = User.find(id)
      uninvite!(user) if user.present?
    end
  end
end

app/controllers/events_controller.rb
require 'icalendar'

class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @time = params[:t] || 'coming'
    case @time
    when 'all'
      @events = Event.visible(current_user)
    when 'passed'
      @events = Event.visible(current_user).passed.page(params[:page])
    else # when 'coming'
      @events = Event.visible(current_user).coming.page(params[:page])
    end

    @view = params[:v] || 'list'

    respond_to do |format|
      format.html
      format.json { render 'index', formats: :json, handlers: :jbuilder }
    end
  end

  def show
    @event = Event.find(params[:id])

    return unless user_signed_in?

    @ticket = current_user.tickets.find_by(event_id: params[:id])

    Notification.find_and_checked!(current_user, @event)
  end

  def new
    @event = current_user.created_events.build
    @event.build_invitation
  end

  def create
    @event = current_user.created_events.build(event_params)
    @event.convert_member_ids_to_invitees(params[:event][:members])

    if @event.save
      redirect_to @event, notice: 'Created'
    else
      render :new
    end
  end

  def edit
    @event = current_user.created_events.find(params[:id])
    @event.convert_invitees_to_member_ids
  end

  def update
    @event = current_user.created_events.find(params[:id])
    @event.convert_member_ids_to_invitees(params[:event][:members])

    if @event.update(event_params)
      redirect_to @event, notice: 'Updated'
    else
      render :new
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.invitation.destroy!
    @event.destroy!
    redirect_to events_path, notice: 'Deleted'
  end

  private

  def event_params
    params.require(:event).permit(
      :title, :description,
      :image_file, :image_file_cache, :remove_image_file, :image_url,
      :visibility, :members,
      invitation_attributes: [:start_time, :end_time, :location, :max_attendees, :deadline]
    )
  end
end

app/views/events/_calendar.html.slim
#calendar

app/views/events/_comma_separator.html.slim
| ,&nbsp

app/views/events/_event.html.slim
= link_to event, class: "list-group-item list-item"
  .row
    .col-lg-1.col-md-1.hidden-sm.hidden-xs.no-padding-right
      = image_tag(event.image, class: "img-responsive center-block") if event.image?

    .col-lg-10.col-md-10.col-sm-11.col-xs-12
      h4.list-group-item-heading
        = event.title

      .list-group-item-text.clearfix
        p.ellipsis
          - if event.description?
            = Markdown.text event.description
          - else
            br

        div
          span.time-slot
            span#start_time.datetime> data-date="#{event.invitation.start_time.to_time}"
            | -
            span#end_time.datetime.time-only< data-date="#{event.invitation.end_time.to_time}"

          - if event.invitation.location.present?
            span.location
              | , @
              = event.invitation.location

          .pull-right
            = event.owner_name

    .col-lg-1.col-md-1.col-sm-1.hidden-xs
      #eventAttendees
        span.number
          span class=(event.include?(current_user) ? 'event-attend' : '')
            = event.attendees.count
          br
        span.unit
          = t('view.event.unit')

app/views/events/_form.html.slim
= form_for(event, class: 'form-horizontal', role: 'form') do |f|
  - if event.errors.any?
    .alert.alert-danger
      ul
        - event.errors.full_messages.each do |msg|
          li #{msg}

  .form-group
    = f.text_field :title, class: 'form-control input-lg event-title', placeholder: t('view.event.title')

  .row
    .col-lg-8.col-md-8.col-sm-12.col-xs-12
      .panel.panel-default
        .panel-heading
          = t('view.event.image')
        .panel-body
          .form-group
            - if event.image_file.present?
              .event-image-area
                = image_tag(event.image_file, class: "img-responsive")
                .label.label-warning.checkbox-remove-image
                  =< f.check_box :remove_image_file
                  span.glyphicon.glyphicon-trash<>
                  = t('view.event.delete')
            = f.file_field :image_file
            = f.hidden_field :image_file_cache

          .form-group
            = f.text_field :image_url, class: 'form-control', placeholder: t('view.event.image_url')

      .panel.panel-default
        .panel-heading
          = t('view.event.detail')
        .panel-body.panel-event
          .row
            .col-lg-2.col-md-2.col-sm-2.col-xs-3
              .pull-right
                = t('view.event.organizer')
            .col-lg-10.col-md-10.col-sm-10.col-xs-9
              = current_user.name

          = f.fields_for :invitation do |f_invitation|
            .row
              .col-lg-2.col-md-2.col-sm-2.col-xs-3
                .pull-right
                  = t('view.event.date_time')
              .col-lg-10.col-md-10.col-sm-10.col-xs-9
                span#eventFormDateTime.hidden
                  span#start_time.datetime>
                  | -
                  span#end_time.datetime.time-only<

                .hidden
                  = f_invitation.text_field :start_time
                  = f_invitation.text_field :end_time

                button.btn-modal-open.btn.btn-default.btn-sm type="button" data-modal="#editDateTimeModal"
                  .glyphicon.glyphicon-calendar aria-hidden="true"
                    = t('view.event.edit')

                #editDateTimeModal.modal.fade tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
                  .modal-dialog.modal-lg
                    .modal-content
                      .modal-body
                        .calendar.calendar-edit.calendar-week

                      .modal-footer
                        button.btn.btn-default type="button" data-dismiss="modal"
                          = t('view.cancel')
                        button#setDateTimeButton.btn.btn-primary type="button"
                          = t('view.ok')

            .row
              .col-lg-2.col-md-2.col-sm-2.col-xs-3
                .pull-right
                  = t('view.event.location')
              .col-lg-10.col-md-10.col-sm-10.col-xs-9
                = f_invitation.text_field :location, class: 'form-control'

            .row
              .col-lg-2.col-md-2.col-sm-2.col-xs-3
                .pull-right
                  = t('view.event.max_attendees')
              .col-lg-2.col-md-2.col-sm-2.col-xs-2
                = f_invitation.number_field :max_attendees, class: 'form-control', min: 0

            .row
              .col-lg-2.col-md-2.col-sm-2.col-xs-3
                .pull-right
                  = t('view.event.deadline')
              .col-lg-10.col-md-10.col-sm-10.col-xs-9
                span#eventFormDeadline
                  span#deadline.datetime.date-only

                .hidden
                  = f_invitation.text_field :deadline

                button.btn-modal-open.btn.btn-default.btn-sm type="button" data-modal="#editDeadlineModal"
                  .glyphicon.glyphicon-calendar aria-hidden="true"
                    = t('view.event.edit')

                #editDeadlineModal.modal.fade tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
                  .modal-dialog.modal-lg
                    .modal-content
                      .modal-body
                        .calendar.calendar-edit.calendar-month

                      .modal-footer
                        button.btn.btn-default type="button" data-dismiss="modal"
                          = t('view.cancel')
                        button.btn-modal-close.btn.btn-primary type="button" data-modal="#editDeadlineModal" data-result="deadline" data-output="#event_invitation_attributes_deadline"
                          = t('view.ok')

          .row
            .col-lg-2.col-md-2.col-sm-2.col-xs-3
              .pull-right
                = t('view.event.members_only')
            .col-lg-10.col-md-10.col-sm-10.col-xs-9
              = f.check_box :visibility, {}, "members_only", "everyone"
              = f.text_field :members, class: 'form-control hidden'

              #members_form
                input class="form-control autocomplete autocomplete-users" placeholder="#{t('view.event.invitees')}"
                #members

          .row
            .col-lg-2.col-md-2.col-sm-2.col-xs-3
              .pull-right
                = t('view.event.description')
            .col-lg-10.col-md-10.col-sm-10.col-xs-9
              .form-group
                ul.nav.nav-tabs role="tablist"
                  li.active
                    a href="#write" role="tab" data-toggle="tab"
                      = t('view.event.text')
                  li
                    a href="#preview" role="tab" data-toggle="tab"
                      = t('view.event.preview')
                .tab-content
                  .tab-pane.fade.in.active#write
                    = f.text_area :description, class: 'form-control', rows: 10
                  .tab-pane.fade#preview
                    .description
                      #markdown

  .form-group.sr-only
    = f.text_field :id

  .button-group
    = f.submit task, class: 'btn btn-primary', data: { disable_with: 'Processing...' }
    = link_to t('view.event.cancel'), event, class: "btn btn-default"

app/views/events/_lf_separator.html.slim
br

app/views/events/_list.html.slim
.pull-right
  - if time == 'passed'
    = link_to t('view.event.coming_events'), root_path(v: 'list'), class: 'btn btn-info'
  - else
    = link_to t('view.event.passed_events'), root_path(v: 'list', t: 'passed'), class: 'btn btn-info'
.clearfix
br

.center
  = paginate events

.list-group
  = render events

.center
  = paginate events

app/views/events/_user_separator.html.slim
| ,&nbsp

app/views/events/edit.html.slim
= render 'form', event: @event, task: t('view.event.update')

app/views/events/index.html.slim
= render @view, events: @events, time: @time

app/views/events/new.html.slim
= render 'form', event: @event, task: t('view.event.create')

app/views/events/show.html.slim
.row
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    h2 #{@event.title}

.row
  .col-lg-8.col-md-8.col-sm-12.col-xs-12
    - if @event.image?
      = image_tag(@event.image, class: "img-responsive center-block")
      .image-spacer

    .panel.panel-default
      .panel-heading
        = t('view.event.detail')
      .panel-body.panel-event
        .row
          .col-lg-2.col-md-2.col-sm-2.col-xs-3
            .pull-right
              = t('view.event.organizer')
          .col-lg-10.col-md-10.col-sm-10.col-xs-9
            = link_to @event.owner_name, @event.owner

        .row
          .col-lg-2.col-md-2.col-sm-2.col-xs-3
            .pull-right
              = t('view.event.date_time')
          .col-lg-10.col-md-10.col-sm-10.col-xs-9
            - if @event.invitation.start_time.present? && @event.invitation.end_time.present?
              => I18n.l(@event.invitation.start_time.to_time)
              | -
              =< I18n.l(@event.invitation.end_time.to_time, format: :short)
            - else
              = "(#{t('view.event.tbd')})"

        .row
          .col-lg-2.col-md-2.col-sm-2.col-xs-3
            .pull-right
              = t('view.event.location')
          .col-lg-10.col-md-10.col-sm-10.col-xs-9
            - if @event.invitation.location.present?
              = @event.invitation.location
            - else
              = "(#{t('view.event.tbd')})"


        .row
          .col-lg-2.col-md-2.col-sm-2.col-xs-3
            .pull-right
              = t('view.event.deadline')
          .col-lg-10.col-md-10.col-sm-10.col-xs-9
            - if @event.invitation.deadline.present?
              => I18n.l(@event.invitation.deadline.to_date)
            - else
              = "(#{t('view.event.tbd')})"

        - if @event.members_only?
          .row
            .col-lg-2.col-md-2.col-sm-2.col-xs-3
              .pull-right
                => t('view.event.members_only')
            .col-lg-10.col-md-10.col-sm-10.col-xs-9
              = render partial: '/users/user', collection: @event.invitees, spacer_template: 'comma_separator'

        - if @event.description?
          .row.description
            .col-lg-2.col-md-2.col-sm-2.col-xs-3
              .pull-right
                = t('view.event.description')
            .col-lg-10.col-md-10.col-sm-10.col-xs-9
              = Markdown.html @event.description

  .col-lg-4.col-md-4.col-sm-12.col-xs-12
    .panel.panel-default
      .panel-heading
        = t('view.event.attendees')
        span
          = " ( #{@event.attendees.count} "
          = "/ #{@event.invitation.max_attendees} " if @event.invitation.max_attendees.present?
          | )

        - if not @event.owner?(current_user)
          .pull-right
            - if not @event.attend?(current_user)
              = link_to t('view.event.attend'), event_tickets_path(@event, @ticket), class: 'btn btn-info', method: :post
            - else
              = link_to t('view.event.cancel'), event_ticket_path(@event, @ticket), class: 'btn btn-danger', method: :delete
      .panel-body.panel-event
        = render partial: '/users/user', collection: @event.attendees, spacer_template: 'lf_separator'

- if @event.owner?(current_user)
  .row
    .col-lg-12.col-md-12.col-sm-12.col-xs-12
      .button-group
        = link_to t('view.event.edit'), edit_event_path(@event), class: 'btn btn-info'
        = link_to t('view.event.delete'), event_path(@event), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?'}