config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :events, :concerns => :paginatable do
    resources :tickets, only: [:create, :destroy]
  end

  devise_for :users
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  resources :users, only: [:index, :show] do
    resources :notifications, only: [:index, :destroy]
  end

  root 'events#index'

  get 'about' => 'static_pages#about'

  mount Markdown::API => '/'

end

app/views/layouts/_fdbk.html.slim
- if ENV["FDBK_URL"].present?
  link rel="import" href="#{ENV["FDBK_URL"]}/pocket-4d.html"
  = stylesheet_link_tag "#{ENV["FDBK_URL"]}/assets/fdbk.css"
  = javascript_include_tag "#{ENV["FDBK_URL"]}/assets/html2canvas.js"
  = javascript_include_tag "#{ENV["FDBK_URL"]}/assets/fdbk.js"

app/views/layouts/_footer.html.slim
footer
  .container
    br
    hr

    .pull-left
      | &copy; 2014-2015 Ikuo Terado

    .center
      | v
      = RailsBase42::Application.config.version

app/views/layouts/_google_tag_manager.html.erb
<% if Rails.env.production? %>
  <!-- Google Tag Manager -->
  <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-WNQDXM"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-WNQDXM');</script>
  <!-- End Google Tag Manager -->
<% end %>

app/views/layouts/_header.html.slim
header.navbar.navbar-default role="navigation"
  .container
    .navbar-header
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Eventor", root_path, class: "navbar-brand", id: "logo"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1

      ul.nav.navbar-nav
        li
          = link_to t('view.calendar'), root_path(v: 'calendar')
        li
          = link_to t('view.list'), root_path
        - if ENV["EVENTOR_BLOG_URL"]
          li
            = link_to t('view.blog'), ENV["EVENTOR_BLOG_URL"]
        li
          = link_to t('view.about'), about_path

      ul.nav.navbar-nav.navbar-right
        li
          .dropdown
            button.btn.btn-default.dropdown-toggle#dropdownMenuAction type="button" data-toggle="dropdown"
              = t('view.create')
              span.caret<
            ul.dropdown-menu role="menu" aria-labelledby="dropdownMenuAction"
              li role="presentation"
                = link_to t('view.event_creation'), new_event_path
        li
          div
            - if !user_signed_in?
              = link_to t('view.sign_in'), sign_in_path, class: "btn btn-success"
            - else
              = link_to user_notifications_path(current_user), class: (current_user.notifications.count > 0 ? 'btn btn-danger' : 'btn btn-default')
                i.glyphicon.glyphicon-envelope
                span#notifications_count<
                  = current_user.notifications.count if current_user.notifications.count > 0

              span.dropdown
                button.btn.btn-default.dropdown-toggle#dropdownMenuUser type="button" data-toggle="dropdown"
                  = current_user.name
                  span.caret<
                ul.dropdown-menu role="menu" aria-labelledby="dropdownMenuUser"
                  li role="presentation"
                    = link_to t('view.my_page'), user_path(current_user)
                  li.divider role="presentation"
                  li role="presentation"
                    = link_to t('view.sign_out'), sign_out_path

  - if user_signed_in?
    = auto_discovery_link_tag(:rss, { controller: :users, action: :show, id: current_user, format: :rss }, title: 'Eventor RSS')

app/views/layouts/application.html.slim
doctype html
html
  head
    title Eventor
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    = render partial: 'layouts/fdbk'

  body
    = render partial: 'layouts/google_tag_manager'
    = render partial: 'layouts/header'

    .container
      - flash.each do |key, value|
        .alert.alert-dismissible class="#{bootstrap_class_for(key)}"
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = value

    .container
      = yield

    = render partial: 'layouts/footer'

    button#fdbk style="position: fixed; right: 0; top: 0;" Send feedback